<?php
 $title = 'My projects';
 $this->headTitle($title);
 ?>
 
 <div class="row" id="banner">
     <div class="thumbnail text-center">
         <img src="<?php echo $this->basePath('img/linedata-banner.jpg') ?>" alt=" linedata banner" class="img-responsive">
         <div class="caption">
             <p>We humanize technology</p>
             <center>
             <a href="https://www.linedata.com">My Linedata View</a>
           </center>
         </div>
     </div>
 </div>
 <div class="project_type_title">Active Projects</div>

 <!--     active project  ---------->
 <table id="active_project"class="proj table">
   <thead>
 <tr class="table_header">
     <th>Name</th>
     <th>Nature</th>
     <th>Brief Description</th>
</tr>
  </thead>
  <tbody>
 <?php foreach ($Project as $row) : ?>
   <tr>
     <td><a href="<?=$this->url('Project', array('id' => $row['project_id'] , 'action' => 'show'))?>"><?php  print_r($row['project_name'])?></a></td>
     <td><?php print_r($row['project_nature_en']) ?></td>
     <td><?php print_r($row['brief_description']) ?></td>
</tr>
 <?php endforeach; ?>
</tbody>
 </table>

 <!--     closed project  ---------->
<div class="project_type_title">Closed Projects</div>
 <table  id="closed_project" class="proj table">
<thead>
<tr class="table_header">
     <th>Name</th>
     <th>Nature</th>
     <th>Brief Description</th>
</tr>
</thead>
<tbody>
  <?php foreach ($Project2 as $row) : ?>
 <tr>
   <td><a href="<?=$this->url('Project', array('id' => $row['project_id'] , 'action' => 'show'))?>"><?php  print_r($row['project_name'])?></a></td>
   <td><?php print_r($row['project_nature_en']) ?></td>
   <td><?php print_r($row['brief_description']) ?></td>
</tr>
<?php endforeach; ?>
</tbody>
 </table>

  <!--   Released projects ---------->
<div class="project_type_title">Released Projects</div>
<table id="onhold_project" class=" proj table">
  <thead>
      <tr class="table_header">
    <th>Name</th>
    <th>Nature</th>
    <th>Brief Description</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($Project3 as $row) : ?>
     <tr>
       <td><a href="<?=$this->url('Project', array('id' => $row['project_id'] , 'action' => 'show'))?>"><?php  print_r($row['project_name'])?></a></td>
       <td><?php print_r($row['project_nature_en']) ?></td>
       <td><?php print_r($row['brief_description']) ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<!--   Proposed projects ---------->
<div class="project_type_title">Proposed Projects</div>
<table id="onhold_project" class=" proj table">
  <thead>
      <tr class="table_header">
    <th>Name</th>
    <th>Nature</th>
    <th>Brief Description</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($Project4 as $row) : ?>
     <tr>
       <td><a href="<?=$this->url('Project', array('id' => $row['project_id'] , 'action' => 'show'))?>"><?php  print_r($row['project_name'])?></a></td>
       <td><?php print_r($row['project_nature_en']) ?></td>
       <td><?php print_r($row['brief_description']) ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="project_type_title">Abandoned Projects</div>
<table id="onhold_project" class=" proj table">
  <thead>
      <tr class="table_header">
    <th>Name</th>
    <th>Nature</th>
    <th>Brief Description</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($Project5 as $row) : ?>
     <tr>
       <td><a href="<?=$this->url('Project', array('id' => $row['project_id'] , 'action' => 'show'))?>"><?php  print_r($row['project_name'])?></a></td>
       <td><?php print_r($row['project_nature_en']) ?></td>
       <td><?php print_r($row['brief_description']) ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
