<?php

 $title = 'My projects';
 $this->headTitle($title);
 ?>
 <img src="<?php echo $this->basePath('img/linedata-banner.jpg') ?>" style="width:100%;height:100%; margin-top: 40px ;" >
 <h3 class="project_type_active">Active Projects</h3>
 <table class="table">
 <tr>
     <th>Partner</th>
     <th>nature</th>
     <th>description</th>
     <th>status</th>
 </tr>
 <?php foreach ($ActiveProjects as $ActiveProject) : ?>
 <tr>
     <td><a href="<?=$this->url('Project', array('name' => $ActiveProject->name, 'action' => 'show'))?>"><?php echo $this->escapeHtml($ActiveProject->name);?></a></td>
     <td><?php echo $this->escapeHtml($ActiveProject->nature);?></td>
     <td><?php echo $this->escapeHtml($ActiveProject->description);?></td>
     <td><?php echo $this->escapeHtml($ActiveProject->status);?></td>
 </tr>
 <?php endforeach; ?>
 </table>
<h3 class="project_type_closed">Closed Projects</h3>
 <table class="table">
 <tr>
     <th>name</th>
     <th>nature</th>
     <th>description</th>
     <th>status</th>
 </tr>
 <?php foreach ($ClosedProjects as $ClosedProject) : ?>
 <tr>
     <td><a href="<?=$this->url('Project', array('name' => $ClosedProject->name, 'action' => 'show'))?>"><?php echo $this->escapeHtml($ClosedProject->name);?></a></td>
     <td><?php echo $this->escapeHtml($ClosedProject->nature);?></td>
     <td><?php echo $this->escapeHtml($ClosedProject->description);?></td>
     <td><?php echo $this->escapeHtml($ClosedProject->status);?></td>
 </tr>
 <?php endforeach; ?>
 </table>
 <h3 class="project_type_hold">On hold Projects</h3>
  <table class="table">
  <tr>
      <th>name</th>
      <th>nature</th>
      <th>description</th>
      <th>status</th>
  </tr>
  <?php foreach ($OnholdProjects as $OnholdProject) : ?>
  <tr>
      <td><a href="<?=$this->url('Project', array('name' => $OnholdProject->name, 'action' => 'show'))?>"><?php echo $this->escapeHtml($OnholdProject->name);?></a></td>
      <td><?php echo $this->escapeHtml($OnholdProject->nature);?></td>
      <td><?php echo $this->escapeHtml($OnholdProject->description);?></td>
      <td><?php echo $this->escapeHtml($OnholdProject->status);?></td>
  </tr>
  <?php endforeach; ?>
  </table>

  <?php foreach($user as $row){
    echo "<b>";  print_r($row['name']); echo "</b>";
    echo "</br>" ;
    print_r($row['description']);
    echo "</br>" ;
    print_r($row['status']);echo "</br>" ;
    print_r($row['global_status']);echo "</br>" ;
    print_r($row['user_email']);echo "</br>" ;
    echo "</br>" ;echo "</br>" ;
}?>

<?php  foreach ($Spreadsheet as $ts) : ?>
  <?php echo "<script>console.log('" . json_encode($ts) . "');</script>"; ?>
<?php endforeach; ?>
