<?php

 $title = 'My projects';
 $this->headTitle($title);
 ?>
 <div class="row" id="banner">
     <div class="thumbnail text-center">
         <img src="<?php echo $this->basePath('img/linedata-banner.jpg') ?>" alt=" linedata banner" class="img-responsive">
         <div class="caption">
             <p>We humanize technology</p>
             <center>
             <a href="https://www.linedata.com">My Linedata View</a>
           </center>
         </div>
     </div>
 </div>
 <div class="project_type_title">Active Projects</div>

 <!--     active project  ---------->
 <table id="active_project"class="proj table">
   <thead>
 <tr class="table_header">
     <th>Name</th>
     <th>Nature</th>
     <th>Brief Description</th>
     <th>Project Leader</th>
 </tr>
  </thead>
  <tbody>
 <?php foreach ($ActiveProjects as $ActiveProject) : ?>
   <tr>
     <td><a href="<?=$this->url('Project', array('name' => $ActiveProject->name, 'action' => 'show'))?>"><?php echo $this->escapeHtml($ActiveProject->name);?></a></td>
     <td><?php echo $this->escapeHtml($ActiveProject->nature);?></td>
     <td><?php echo $this->escapeHtml($ActiveProject->description);?></td>
     <td>John doe</td>
 </tr>
 <?php endforeach; ?>
</tbody>
 </table>

 <!--     closed project  ---------->
<div class="project_type_title">Closed Projects</div>
 <table  id="closed_project" class="proj table">
<thead>
<tr class="table_header">
     <th>Name</th>
     <th>Nature</th>
     <th>Brief Description</th>
     <th>Project Leader</th>
 </tr>
</thead>
<tbody>
  <?php foreach ($ClosedProjects as $ClosedProject) : ?>
 <tr>
     <td><a href="<?=$this->url('Project', array('name' => $ClosedProject->name, 'action' => 'show'))?>"><?php echo $this->escapeHtml($ClosedProject->name);?></a></td>
     <td><?php echo $this->escapeHtml($ClosedProject->nature);?></td>
     <td><?php echo $this->escapeHtml($ClosedProject->description);?></td>
     <td>John doe</td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>

  <!--   Released projects ---------->
<div class="project_type_title">Released Projects</div>
<table id="onhold_project" class=" proj table">
  <thead>
      <tr class="table_header">
    <th>Name</th>
    <th>Nature</th>
    <th>Brief Description</th>
    <th>Project Leader</th>
      </tr>
    </thead>

<tbody>
<tr>
   <td>Project 1 </td>
<td>fix integration</td>
<td>waiting for EMEA region</td>
<td>John doe</td>
</tr>
<tr>
   <td>Project 2 </td>
<td>missing feature</td>
<td>	this is a test description 5 regions</td>
<td>John doe</td>
</tr>
  </tbody>
</table>
<!--   Proposed projects ---------->
<div class="project_type_title">Proposed Projects</div>
<table id="onhold_project" class=" proj table">
  <thead>
      <tr class="table_header">
    <th>Name</th>
    <th>Nature</th>
    <th>Brief Description</th>
    <th>Project Leader</th>
      </tr>
    </thead>

<tbody>
  <tr>
     <td>Project 1 </td>
  <td>fix integration</td>
  <td>waiting for EMEA region</td>
  <td>John doe</td>
  </tr>
  <tr>
     <td>Project 2 </td>
  <td>missing feature</td>
  <td>	this is a test description 5 regions</td>
  <td>John doe</td>
  </tr>
  </tbody>
</table>
<div class="project_type_title">Abandoned Projects</div>
<table id="onhold_project" class=" proj table">
  <thead>
      <tr class="table_header">
    <th>Name</th>
    <th>Nature</th>
    <th>Brief Description</th>
    <th>Project Leader</th>
      </tr>
    </thead>

<tbody>
  <tr>
     <td>Project 1 </td>
  <td>fix integration</td>
  <td>waiting for EMEA region</td>
  <td>John doe</td>
  </tr>
  <tr>
     <td>Project 2 </td>
  <td>missing feature</td>
  <td>	this is a test description 5 regions</td>
  <td>John doe</td>
  </tr>
  </tbody>
</table>
  <?php /* -------------------------------------------how to display array object ---------------------------------
  foreach($user as $row){
    echo "<b>";  print_r($row['name']); echo "</b>";
    echo "</br>" ;
    print_r($row['description']);
    echo "</br>" ;
    print_r($row['status']);echo "</br>" ;
    print_r($row['global_status']);echo "</br>" ;
    print_r($row['user_email']);echo "</br>" ;
    echo "</br>" ;echo "</br>" ;
}*/?>
<?php
 foreach ($Project as $row){
   echo "<b>";  print_r($row['global_status']); echo "</b>";
   echo "</br>" ;
 echo "</br>" ;
}?>
