<div class="project_name"><h2><?php
 echo $this->escapeHtml($Project->name);
 ?></h2></div>
<div class="lifecycle col-md-12">
<center>  <h2>  Lifecycle Space </h2> </center>
  <div class="timeline" data-mode="horizontal" data-visible-items="3">
   <div class="timeline__wrap">
     <div class="timeline__items">
       <div class="timeline__item">
         <div class="timeline__content">
          <b> specification </b> / description : Lorem ipsum dolor sit amet, an eos dico utinam placerat.
            Te luptatum suscipiantur usu. Quot indoctum gubergren at quo, vel an possim insolens oportere.
             Duo ad blandit percipitur, vim in epicurei incorrupte. <br>
             <b>21/08/2018</b>
         </div>
       </div>
       <div class="timeline__item">
         <div class="timeline__content">
          <b> Conception </b> / description : Lorem ipsum dolor sit amet, an eos dico utinam placerat.
            Te luptatum suscipiantur usu. Quot indoctum gubergren at quo, vel an possim insolens oportere.
             Duo ad blandit percipitur, vim in epicurei incorrupte. <br>
             <b style="color: red ">27/08/2018</b>
         </div>
       </div>
       <div class="timeline__item">
         <div class="timeline__content">
          <b> Integration QA </b> / description : Lorem ipsum dolor sit amet, an eos dico utinam placerat.
            Te luptatum suscipiantur usu. Quot indoctum gubergren at quo, vel an possim insolens oportere.
             Duo ad blandit percipitur, vim in epicurei incorrupte. <br>
             <b style="color: red ">27/08/2018</b>
         </div>
       </div>

       <div class="timeline__item">
         <div class="timeline__content">
          <b> Integration Certification </b> / description : Lorem ipsum dolor sit amet, an eos dico utinam placerat.
            Te luptatum suscipiantur usu. Quot indoctum gubergren at quo, vel an possim insolens oportere.
             Duo ad blandit percipitur, vim in epicurei incorrupte. <br>
             <b>27/08/2018</b>
         </div>
       </div>
       <div class="timeline__item">
         <div class="timeline__content">
           Your content / markup
         </div>
       </div>
     </div>
   </div>
 </div>
</div>

<div class="status col-md-4">
  <h2 style="color: white"> current status </h2>
</div>
<div class="list_people col-md-8">
<h2> list of people working on the project</h2>
</div>
<div class="latest_changes col-md-6">
  <h2 style="color: white"> latest changes done on the project (current status)  </h2>
</div>
<div class="stats col-md-6">
  <h2 style="color: white">stats space</h2>
</div>
<div class="related_documents col-md-12">
  <div class="panel panel-danger">
  <div class="panel-heading">Related Documents</div>
  <table class="table">
    <thead> <tr> <th>Name</th> <th>Size</th> <th>Type</th> <th>Date</th> <th>Modified</th><th>Author</th> </tr> </thead>
    <tbody> <tr> <th scope="row">UBSoptaigo.png</th> <td>84.84 KB</td><td>PNG</td> <td>Tue, 06 Mar 2018 10:22:05</td> <td> Mon, 06 Aug 2018 10:22:05</td><td>Anastasia Allan</td> </tr>
       <tr> <th scope="row">UBS_option_Issue_call.msg</th>   <td> 51.95 KB</td> <td>MSG</td><td>Tue, 24 Jul 2018 10:34:21 </td> <td>Thu, 06 Sep 2018 10:22:05 </td><td>Martine Estes</td> </tr>
          <tr> <th scope="row">LVUBS_option_interface.zip</th> <td>18.59 MB</td><td>ZIP</td> <td>Fri, 13 Jul 2018 10:34:21</td> <td>Sat, 06 Oct 2018 10:22:05</td> <td>Fabian Rahman</td>
           </tr>
            </tbody>
  </table>
</div>
</div>
<div class="latest_journal_entries col-md-12">
  <div class="panel panel-info">
  <div class="panel-heading">Recent journal / comment </div>
  <table class="table">
    <thead> <tr> <th>#</th> <th> Entery date</th> <th>Journal entry/comment</th> <th>links</th> </tr> </thead>
    <tbody> <tr> <th scope="row">Lap-191</th> <td>Monday, December 31, 2018</td> <td>We are waiting for the client to give us permission</td> <td><a href="#">https://www.jira.com/?utm_source=ken&utm_medium=mail&utm_campaign=linedata</a></td> </tr>
       <tr> <th scope="row">2045863</th>   <td>Friday, December 28, 2018</td> <td>Ready for release </td> <td><a href="#">https://www.ken.com/?utm_source=ken&utm_medium=mail&utm_campaign=linedata</a></td> </tr>
          <tr> <th scope="row">22015678</th> <td>Friday, December 7, 2018 </td> <td>Test and failed in 75.0.2 build 37300</td> <td><a href="#">https://www.example.com/?utm_source=ken&utm_medium=mail&utm_campaign=linedata</a></td>
           </tr>
            </tbody>
  </table>
</div>
</div>
