<div class="row" id="banner">
    <div class="thumbnail text-center">
        <img src="<?php echo $this->basePath('img/linedata-banner.jpg') ?>" alt=" linedata banner" class="img-responsive">
        <div class="caption">
            <p> <?php /*echo  $this->escapeHtml($Project->name) */?> Project name<div style="color:#DD0031">
                   <?php /* echo  $this->escapeHtml($Project->status) */?> Certification </div>  </p>
            <center>
            <a href="<?php echo $this->url('Project') ?>">All Projects</a>
            <a href="https://www.linedata.com">My Linedata View</a>
          </center>
        </div>
    </div>
</div>

<div class="latest_changes_journal col-md-12">
  last change : Lorem ipsum dolor sit amet, id lorem mazim quando nam,
   ipsum eleifend patrioque qui ad. Cu interesset delicatissimi eam. His elit putent at
</div>

<div class="lifecycle col-md-12">
  <center>  <div class="section_title">Timeline Space </div> </center>
  <div class="timeline" data-mode="horizontal" data-visible-items="3">
   <div class="timeline__wrap">
     <div class="timeline__items">
       <div class="timeline__item">
         <div class="timeline__content">
          <b> specification </b>: Lorem ipsum dolor sit amet. <br>
             <b class="timeline_date">21/08/2018</b>
         </div>
       </div>
       <div class="timeline__item">
         <div class="timeline__content">
          <b> Conception </b>: Lorem ipsum dolor sit ames. <br>
             <b class="timeline_date">27/08/2018</b>
         </div>
       </div>
       <div class="timeline__item">
         <div class="timeline__content">
          <b> Integration QA </b>: Lorem ipsum dolor sit amet. <br>
             <b class="timeline_date">27/08/2018</b>
         </div>
       </div>
       <div class="timeline__item">
         <div class="timeline__content">
          <b>Certification </b>Lorem ipsum dolor sit amet. <br>
             <b class="timeline_date">27/08/2018</b>
         </div>
       </div>
       <div class="timeline__item">
         <div class="timeline__content">
           Your content / markup
         </div>
       </div>
     </div>
   </div>
 </div>
</div>
<div class="list_people col-md-12">
<center><div class="section_title"> Teams</div></center>
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#sales">Sales</a></li>
  <li><a data-toggle="tab" href="#dev">Developement</a></li>
  <li><a data-toggle="tab" href="#test">Testing</a></li>
  <li><a data-toggle="tab" href="#certif">Certification</a></li>
  <li><a data-toggle="tab" href="#release">Release</a></li>
</ul>
<div class="tab-content">
  <div id="sales" class="tab-pane fade in active">
    <h3>Sales Team</h3>
    <table class="table">
      <thead> <tr> <th>name</th> <th>Role</th> </tr> </thead>
      <tbody> <tr> <th scope="row">Rhodri Searle &nbsp <a href="mailto:joedoe@gmail.com" title="send mail to joe doe"> <span class="glyphicon glyphicon-send" aria-hidden="true"></span></a></th><td>Senior QA</td> </tr>
         <tr> <th scope="row">Farhana Chapman  &nbsp <a href="mailto:joedoe@gmail.com" title="send mail to joe doe"> <span class="glyphicon glyphicon-send" aria-hidden="true"></span></a></th> <td>Data Manager</td> </tr>
            <tr> <th scope="row">Jakob Mills  &nbsp <a href="mailto:joedoe@gmail.com" title="send mail to joe doe"> <span class="glyphicon glyphicon-send" aria-hidden="true"></span></a></th><td>Sales Strategy</td>
             </tr>
              </tbody>
    </table>
  </div>
  <div id="dev" class="tab-pane fade">
    <h3>Dev Team</h3>
    <table class="table">
      <thead> <tr> <th>name</th> <th>Role</th> </tr> </thead>
      <tbody> <tr> <th scope="row">Rhodri Searle</th><td>Senior QA</td></tr>
         <tr> <th scope="row">Farhana Chapman</th>   <td>Data Manager</td></tr>
            <tr> <th scope="row">Jakob Mills</th> <td>Sales Strategy</td></tr>
              </tbody>
    </table>
  </div>
  <div id="test" class="tab-pane fade">
    <h3>Test Team</h3>
    <table class="table">
      <thead> <tr> <th>name</th> <th>Role</th> </tr> </thead>
      <tbody> <tr> <th scope="row">Patsy Mata</th>  <td>Senior QA</td> </tr>
         <tr> <th scope="row">Farhana Chapman</th>    <td>Data Manager</td> </tr>
            <tr> <th scope="row">Jakob Mills</th> <td>Manager</td>
             </tr>
              </tbody>
    </table>
  </div>
  <div id="certif" class="tab-pane fade">
    <h3>Certification Team</h3>
    <table class="table">
      <thead> <tr> <th>name</th> <th>Role</th> </tr> </thead>
      <tbody> <tr> <th scope="row">Rhodri Searle</th><td>Senior QA</td> </tr>
         <tr> <th scope="row">Farhana Chapman</th><td>Data Manager</td> </tr>
            <tr> <th scope="row">Jakob Mills</th><td>Sales Strategy</td>
             </tr>
             <tr> <th scope="row">Eduard Sanford</th><td>Sales Strategy</td>
              </tr>
              </tbody>
    </table>
  </div>
  <div id="release" class="tab-pane fade">
    <h3>Release Team</h3>
    <table class="table">
      <thead> <tr> <th>name</th> <th>Role</th> </tr> </thead>
      <tbody> <tr> <th scope="row">Rhodri Searle</th><td>Senior QA</td> </tr>
         <tr> <th scope="row">Farhana Chapman</th><td>Data Manager</td> </tr>
            <tr> <th scope="row">Jakob Mills</th><td>Sales Strategy</td>
             </tr>
             <tr> <th scope="row">Cairo Haynes</th><td>Sales Strategy</td>
              </tr>
              <tr> <th scope="row">Arandeep Salas</th> <td>Sales Strategy</td>
               </tr>
              </tbody>
    </table>
  </div>
</div>
</div>
<div class="issue_tracker col-md-12">
  <center><div class="section_title"> Issues Tracker </div> </center>
  <table id="issue_tracker" class="issue_tracker table">
    <thead>
  <tr class="table_header">
      <th>Call Type</th>
      <th> Open</th>
      <th> In Dev </th>
      <th> Testing</th>
      <th> Closed</th>
  </tr>
   </thead>
   <tbody>
    <tr>
      <td>womeg1</td>
      <td>womeg2</td>
      <td>womeg3</td>
      <td>womeg4</td>
      <td>womeg5</td>
  </tr>
  </tbody>
  </table>
</div>
<div class="latest_changes col-md-6">
<center><div class="section_title"> Certifications </div> </center>
  <div class="panel panel-success">
      <div class="panel-heading">Tested Versions</div>
      <div class="panel-body"><ul>
        <li>7.1.3.0003</li>
        <li>7.4.2.0000</li>
      </ul>
      </div>
    </div>
    <div class="panel panel-danger">
        <div class="panel-heading">Versions To Be Tested</div>
        <div class="panel-body"><ul>
          <li>7.5.2.0003</li>
          <li>7.5.1.0000</li>
        </ul></div>
      </div>
</div>
<div class="stats col-md-6">
  <center><div class="section_title">Statistics</div><center>
  <canvas id="myChart"></canvas>
</div>
<div class="related_documents col-md-12">
  <div class="panel panel-default">
  <div class="panel-heading">Related Documents</div>
  <table class="table">
    <thead> <tr> <th>Name</th> <th>Size</th> <th>Type</th> <th>Date</th> <th>Modified</th><th>Author</th> </tr> </thead>
    <tbody> <tr> <th scope="row">UBSoptaigo.png</th> <td>84.84 KB</td><td>PNG</td> <td>Tue, 06 Mar 2018 10:22:05</td> <td> Mon, 06 Aug 2018 10:22:05</td><td>Anastasia Allan</td> </tr>
       <tr> <th scope="row">UBS_option_Issue_call.msg</th>   <td> 51.95 KB</td> <td>MSG</td><td>Tue, 24 Jul 2018 10:34:21 </td> <td>Thu, 06 Sep 2018 10:22:05 </td><td>Martine Estes</td> </tr>
          <tr> <th scope="row">LVUBS_option_interface.zip</th> <td>18.59 MB</td><td>ZIP</td> <td>Fri, 13 Jul 2018 10:34:21</td> <td>Sat, 06 Oct 2018 10:22:05</td> <td>Fabian Rahman</td>
           </tr>
            </tbody>
  </table>
</div>
</div>
<div class="latest_journal_entries col-md-12">
  <div class="panel panel-default">
  <div class="panel-heading"><b>Recent journal / comment </b></div>
  <table class="table">
    <thead> <tr> <th>#</th> <th> Entery date</th> <th>Journal entry/comment</th> </tr> </thead>
    <tbody> <tr> <th scope="row"> <a href="#"> Lap-191</a></th> <td>Monday, December 31, 2018</td> <td>We are waiting for the client to give us permission</td></tr>
      <tr> <th scope="row"><a href="#"> 2045863</a></th>   <td>Friday, December 28, 2018</td> <td>Ready for release </td></tr>
            <tr> <th scope="row"><a href="#">22015678</a></th> <td>Friday, December 7, 2018 </td> <td>Test and failed in 75.0.2 build 37300</td></tr>
            </tbody>
  </table>
</div>
</div>
<?php
 foreach ($Project as $row){
   echo "<b>";  print_r($row['project_id']); print_r($row['project_name']); print_r($row['brief_description']); print_r($row['project_nature_en']); print_r($row['project_type']);echo  "</b>";
   echo "</br>" ;
 echo "</br>" ;
}?>
<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["US", "EMEA", "APAC"],
        datasets: [{
            label: 'Developement',
            data: [100, 75, 60],
            backgroundColor: [
                'rgba(0, 0, 0, 0.7)',
                'rgba(0, 0, 0, 0.7)',
                'rgba(0, 0, 0, 0.7)'
            ],
            borderColor: [
                'rgba(149, 165, 166,0.5)',
                'rgba(149, 165, 166,0.5)',
                'rgba(149, 165, 166,0.5)'
            ],
            borderWidth: 1
        },
        {
            label: 'Testing',
            data: [60, 100, 70],
            backgroundColor: [
                'rgba(149, 165, 166,0.7)',
                'rgba(149, 165, 166,0.7)',
                'rgba(149, 165, 166,0.7)'
            ],
            borderColor: [
                'rgba(149, 165, 166,0.5)',
                'rgba(149, 165, 166,0.5)',
                'rgba(149, 165, 166,0.5)'
            ],
            borderWidth: 1
        },
        {
            label: 'Certification',
            data: [75, 70, 100],
            backgroundColor: [
                'rgba(183, 25, 40, 0.7)',
                'rgba(183, 25, 40, 0.7)',
                'rgba(183, 25, 40, 0.7)'
            ],
            borderColor: [
                'rgba(149, 165, 166,0.5)',
                'rgba(149, 165, 166,0.5)',
                'rgba(149, 165, 166,0.5)'
            ],
            borderWidth: 1
        }
      ]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>
<script type="text/javascript">
/* Formatting function for row details - modify as you need */
function format ( d ) {
  // `d` is the original data object for the row
  return '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">'+
      '<tr>'+
          '<td>Full name:</td>'+
          '<td>'+d.name+'</td>'+
      '</tr>'+
      '<tr>'+
          '<td>Extension number:</td>'+
          '<td>'+d.extn+'</td>'+
      '</tr>'+
      '<tr>'+
          '<td>Extra info:</td>'+
          '<td>And any further details here (images etc)...</td>'+
      '</tr>'+
  '</table>';
}

$(document).ready(function() {
    var table = $('#example').DataTable( {
        "ajax": "../ajax/data/objects.txt",
        "columns": [
            {
                "className":      'details-control',
                "orderable":      false,
                "data":           null,
                "defaultContent": ''
            },
            { "data": "name" },
            { "data": "position" },
            { "data": "office" },
            { "data": "salary" }
        ],
        "order": [[1, 'asc']]
    } );

    // Add event listener for opening and closing details
    $('#issue_tracker tbody').on('click', 'td.details-control', function () {
        var tr = $(this).closest('tr');
        var row = table.row( tr );

        if ( row.child.isShown() ) {
            // This row is already open - close it
            row.child.hide();
            tr.removeClass('shown');
        }
        else {
            // Open this row
            row.child( format(row.data()) ).show();
            tr.addClass('shown');
        }
    } );
} );
</script>
