<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ProjectManagement'. $this->translate('Project Management App'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon-linedata.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/timeline.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                         ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/timeline.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
                  <!-- Scripts for statistics ,Raleway font and dataTables  -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,700,800" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jqc-1.12.4/dt-1.10.18/r-2.2.2/datatables.min.css"/>
        <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jqc-1.12.4/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
    </head>
    <body>
      <?php $project_name = "ok"; ?>
        <nav class="navbar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/linedata-logo.png') ?>" alt="." style="height:20px; " />&nbsp;<?php echo $this->translate('ProjectManagement') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav pull-right">
                        <li class="menu_item"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                          <li class="menu_item"><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('Login') ?></a></li>
                            <li class="menu_item"><a href="<?php echo $this->url('user_logout') ?>"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></a></li>
                         <li class="menu_item dropdown"><a href=# class="dropbtn"><span class="glyphicon glyphicon-time" aria-hidden="true"></span></a>
                            <div id="dropdown-content-time" class="dropdown-content-time">
                           <a href="#" class="timezone">Tunis </a><div class="tunis-clock"></div><br>
                             <a href="#" class="timezone">Boston</a> <div class="boston-clock"></div> <br>
                             <a href="#" class="timezone">London</a> <div class="london-clock"></div><br>
                             <a href="#" class="timezone" >Paris</a> <div class="paris-clock"></div><br>
                             <a href="#" class="timezone" >Riga</a> <div class="riga-clock"></div><br>
                             <a href="#" class="timezone" >Hong Kong</a> <div class="hongkong-clock"></div>
                           </div>

                         </li>

                          </div>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
            </footer>
        </div> <!-- /container -->
                  <!-- Script for the dataTables-->
        <script type="text/javascript">
        $(document).ready( function () {
    $('table.proj').DataTable();
} );
        //--------------------------------- timeline script------------------------------------------
        timeline(document.querySelectorAll('.timeline'));
        </script>
        <script type="text/javascript">

        //--------------------------------- clock script (need a redo !!!!)------------------------------------------
        function clock() {
          var tunis_time = new Date() ; tunis_time.setUTCHours(15);
          var boston_time = new Date(); boston_time.setUTCHours(10);
          var paris_time = new Date();  paris_time.setUTCHours(16);
          var london_time = new Date();  london_time.setUTCHours(15);
          var riga_time = new Date();  riga_time.setUTCHours(15);
          var hongkong_time = new Date();  hongkong_time.setUTCHours(22);
        tnhours = tunis_time.getUTCHours(),
        tnminutes =  tunis_time.getUTCMinutes(),
        tnseconds = tunis_time.getUTCSeconds();
        bshours = boston_time.getUTCHours(),
        bsminutes =  boston_time.getUTCMinutes(),
        bsseconds = boston_time.getUTCSeconds();
        pahours = paris_time.getUTCHours(),
        paminutes =  paris_time.getUTCMinutes(),
        paseconds = paris_time.getUTCSeconds();
        lonhours = london_time.getUTCHours(),
        lonminutes =  london_time.getUTCMinutes(),
        lonseconds = london_time.getUTCSeconds();
        rigahours = riga_time.getUTCHours(),
        rigaminutes =  riga_time.getUTCMinutes(),
        rigaseconds = riga_time.getUTCSeconds();
        hkhours = hongkong_time.getUTCHours(),
        hkminutes =  hongkong_time.getUTCMinutes(),
    //    hkseconds = hongkong_time.getUTCSeconds();
        document.querySelectorAll('.tunis-clock')[0].innerHTML  = harold(tnhours) + ":" + harold(tnminutes) + ":" + harold(tnseconds);
        document.querySelectorAll('.boston-clock')[0].innerHTML  = harold(bshours) + ":" + harold(bsminutes) + ":" + harold(bsseconds);
        document.querySelectorAll('.riga-clock')[0].innerHTML  = harold(rigahours) + ":" + harold(rigaminutes) + ":" + harold(rigaseconds);
        document.querySelectorAll('.paris-clock')[0].innerHTML  = harold(pahours) + ":" + harold(paminutes) + ":" + harold(paseconds);
        document.querySelectorAll('.hongkong-clock')[0].innerHTML  = harold(hkhours) + ":" + harold(hkminutes) + ":" /*+ harold(hkseconds)*/;
        document.querySelectorAll('.london-clock')[0].innerHTML  = harold(lonhours) + ":" + harold(lonminutes) + ":" + harold(lonseconds);

        function harold(standIn) {
          if (standIn < 10) {
            standIn = '0' + standIn
            }
          return standIn;
          }
        }
        setInterval(clock, 1000);
        </script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
