<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ProjectManagement'. $this->translate('Project Management App'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon-linedata.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/timeline.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/timeline.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
                  <!-- Scripts for statistics and Raleway font -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,700,800" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/linedata-logo.png') ?>" alt="." style="height:20px; " />&nbsp;<?php echo $this->translate('ProjectManagement') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav pull-right">
                        <li class="menu_item"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                          <li class="menu_item"><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('Login') ?></a></li>
                            <li class="menu_item"><a href="<?php echo $this->url('user_logout') ?>"><?php echo $this->translate('Logout') ?></a></li>
                            <li class="menu_item"><a href=#><div class="clock"></div></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
            </footer>
        </div> <!-- /container -->
                  <!-- Script for the initiation of the Timeline -->
        <script type="text/javascript">

        //--------------------------------- timeline script------------------------------------------
        timeline(document.querySelectorAll('.timeline'));
        </script>
        <script type="text/javascript">

        //--------------------------------- clock script------------------------------------------
        function clock() {
          var time = new Date(),
        hours = time.getHours(),
        minutes = time.getMinutes(),
        seconds = time.getSeconds();
        document.querySelectorAll('.clock')[0].innerHTML = harold(hours) + ":" + harold(minutes) + ":" + harold(seconds);
        function harold(standIn) {
          if (standIn < 10) {
            standIn = '0' + standIn
            }
          return standIn;
          }
        }
        setInterval(clock, 1000);
        </script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
