<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sProject Management%s'), '<span class="zf-red">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sProject Management Application%s.
    You are currently running Zend Framework version %s.
     This Application can serve as a simple starting point for you to begin building your Project Management Application on ZF2.'),
     '<a href="https://github.com/ysfgouicem/ProjectManagementApp" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?>
   </p>
</div>
